spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candy_shop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  security:
#    user:
#      name: root
#      password: password
#      roles: "ADMIN"
